env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
ignorePatterns: [ '*.js', 'types', 'index.d.ts', 'index.ts' ]
plugins:
  - '@typescript-eslint'
rules:
  # @typescript-eslint rules
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-ignore:
        descriptionFormat: '^: @test|@to-fix|@node-type'
  "@typescript-eslint/ban-types":
    - error
    - types:
        "{}": false
      extendDefaults: true
  # eslint core rules
  computed-property-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - always
  space-in-parens:
    - warn
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  newline-before-return: error
  curly:
    - error
    - multi-or-nest
  indent:
    - warn
    - 2
    - SwitchCase: 1
  object-curly-spacing:
    - warn
    - always
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  eqeqeq:
    - error
    - always
  no-return-await: error
  capitalized-comments:
    - warn
    - always
    - line:
        ignorePattern: todo
      block:
        ignoreInlineComments: true
        ignorePattern: todo
  comma-spacing:
    - warn
    - before: false
      after: true
  no-trailing-spaces:
    - error
    - ignoreComments: true
  switch-colon-spacing: warn
  no-fallthrough:
    - error
    - commentPattern: break[\\s\\w]*omitted
  default-case:
    - warn
    - commentPattern: 'skip\\sdefault'